site_name: Dicaeopolis' Wiki

theme:
  name: material
  custom_dir: docs/overrides
  custom_dir: overrides
  favicon: favicon.png
  logo: favicon.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.titles
    - navigation.tabs
    - navigation.indexes
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
  language: zh

hooks:
  - docs/overrides/hooks/reading_time.py    # 阅读时间统计，但是承担了很多额外功能，已经不是本来的样子了

extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  # - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.magiclink
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.arithmatex:  
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      # baselevel: 2
      # toc_depth: 3  # 控制标题层级深度
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mermaid2
  - encryptcontent:
      title_prefix: '[Protected]'
      summary: '不给你看😝'
      placeholder: '口令输对了才能看哦'
      decryption_failure_message: '输错了哦~'
      encryption_info_message: '👇👇👇👇👇👇'

extra_css:
  - themes/css/custom.css
  - themes/css/simpleLightbox.min.css
  - themes/css/pied_piper.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  - stylesheets/customize.css  #按钮圆角化
  - assets/css/custom.css
 
extra_javascript:
  - assets/js/custom.js
  - themes/js/custom.js
  - themes/js/simpleLightbox.min.js
  - themes/js/optionalConfig.js
  - themes/js/mermaidloader.js
  - themes/js/umlconvert.js
  - themes/js/mathjax.js
  - themes/js/katex.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.17.1/flowchart.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.6/underscore-min.js
  - https://cdn.jsdelivr.net/npm/@mermaid-js/mermaid-mindmap@9.3.0/dist/diagram-definition.0faef4c2.min.js
  - https://cdn.jsdelivr.net/npm/markdown-it-plantuml@1.4.1/index.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-svg-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  

nav:
  - 天文摄影理论和实践:
    - 'astronomy/index.md'
    - 关于（半）自动寻星与拍摄的一点思路: 'astronomy/GOTO.md'
    - 一种简易的半自动寻星法: 'astronomy/track.md'
    - 深空影集: 'astronomy/gallery.md'
    - 看不见北极星怎么办: 'astronomy/polar.md'
    - 方位调节: 'astronomy/方位调节.md'
    - 纬度调节: 'astronomy/纬度调节.md'
  - 校内课程知识:
    - 'campus-sources/index.md'
    - 《计算机组成与设计》部分历年题目题解: 'campus-sources/SDC-exams.md'
    - 《离散数学》部分期末题目题解: 'campus-sources/Discrete_exams.md'
    - 离散期末复习提纲: 'campus-sources/Discrete_notes.md'
    - 《离散数学》课程作业与笔记归档: 'campus-sources/Descrete_assignments.md'
    - 《概率论与数理统计》课程作业与笔记归档: 'campus-sources/Prob_Stats_assignments.md'
    - 《计算机组成原理》理论课程作业与笔记归档: 'campus-sources/SDC_assignments.md'
    - 《大学物理B下》课程作业与笔记归档: 'campus-sources/PU_Bii_assignments.md'
    - <i class="fas fa-calculator"></i> 二进制乘法可视化工具: 'campus-sources/binmul.md'
    - 本科教科书电子资源: 'campus-sources/textbook.md'
    - 《数据结构》划重点笔记: 'campus-sources/ds-keynote.md'
    - 《数据结构》期末复习题题解: 'campus-sources/ds-write-up.md'
    - 自动签到脚本: 'campus-sources/autosignin.md'
  - 深度神经网络:
    - 'DNN/index.md'
    - 如何做四六级考试的段落匹配题: 'DNN/match.md'
    - 前馈神经网络的反向传播: 'DNN/BP.md'
    - RL学习笔记 - 上篇: 'DNN/RL.md'
    - SMO 算法的推导: 'DNN/SVM_SMO.md'
    - Wp:
      - MISC-AI 方向 WriteUp: 'DNN/WP/aiwp.md'
    - 深度学习模型攻击理论与复现归档:
      - 'DNN/model-attack/index.md'
      - HSJA 攻击: 'DNN/model-attack/hsja.md'
      - BadNets: 'DNN/model-attack/BadNets.md'
      - C&W 攻击: 'DNN/model-attack/CandW.md'
      - PGD 攻击: 'DNN/model-attack/pgd.md'
      - FGSM 攻击: 'DNN/model-attack/fgsm.md'
    - 深度学习相关模型理论与复现归档:
      - 'DNN/model-expr/index.md'
      - '扩散模型理论篇: 从多阶段变分自编码器到概率流常微分方程采样器系列': 'DNN/model-expr/DDPM.md'
      - 图像语义分割和目标检测相关模型复现手记: 'DNN/model-expr/S-and-D-models-replication.md'
      - 图像分类相关模型复现手记: 'DNN/model-expr/Image-models-replication.md'
      - DC-GAN 老婆生成器: 'DNN/model-expr/DC-GAN-老婆生成器.md'
    - 优化器:
      - 'DNN/optimizer/index.md'
      - 后续的写作计划: 'DNN/optimizer/misc.md'
      - 符号梯度下降: 'DNN/optimizer/SignGD.md'
      - 自适应学习率改进策略: 'DNN/optimizer/Adaptive.md'
      - SGD 系列算法: 'DNN/optimizer/SGD.md'
  - 配置和杂谈笔记:
    - 'misc/index.md'
    - 功能测试页面: 'misc/test.md'
    - 一条Web对话风格约束提示词: 'misc/prompt.md'
  - 传统算法与性能:
    - 'algorithm/index.md'
    - STL的一些性能测试: 'algorithm/benchmark-on-stl.md'
    - 嗯造轮子: 'algorithm/stl-wheels.md'
    - 整数环取模模板: 'algorithm/template-on-numeric-ring.md'